### ISSUE TITLE
there exist a similar solution https://github.com/kleros/action-callback-bots  

### ISSUE THREAD

**Issue by orenyodfat** [daostack/web3-transaction-batcher#1]
how about using this package ? https://www.npmjs.com/package/web3-batched-send/v/1.0.2

**Comment by jellegerbrandy** [comment]
That package was why this repo was started :-)

- it filters out failing tarnsactions from the list, which can be good for certain use cases, but in general does not seem a good idea
- the batchedSend method does not follow the web3js api for sending transactions, and so would be cumbersome to integrate
- it is nice to create transactions with web3 in by calling `MyContract.myMethod(...myArgs)`  and passing that to the batch sender.
