### ISSUE TITLE
Will this package work directly in BSC network ?

### ISSUE THREAD

**Issue by frodoe7** [daostack/web3-transaction-batcher#16]
I'm asking if this package will work directly in BSC network ?
or I have to do some work for the the contract ? build / deploy and publish it to the BSC network for example?

**Comment by leviadam** [comment]
Hi @frodoe7,

I think this was not deployed on BSC, you can do that manually.

**Comment by frodoe7** [comment]
> Hi @frodoe7,
> 
> I think this was not deployed on BSC, you can do that manually.

Ah got it,
will deploy it,
